/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFp/W8vHEpDBDc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/W8vHEpDBDc= >>
// ----------- >>
public class DecideToStartOrToQuitForm {
  // ----------- << method.annotations@AAAAAAFp/XRHE0rj494= >>
  // ----------- >>
  public void choose(int decision) {
  // ----------- << method.body@AAAAAAFp/XRHE0rj494= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFp/W8vHEpDBDc= >>
// ----------- >>
}