/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

import application.BoardData;
import application.Constants.*;

public class GameBoardDisplay {

  public void presentBoard(BoardData board, int n) {
	  String spacesToAdd;
	  State cellsState[][] = board.getCellsState();
	  State stateToPrint;
	  System.out.println("\nTic Tac Toe Board:");
	  	  for(int i = 0; i < n;i++) {
		  System.out.println();
		  for(int j=0;j < n;j++) {
			  stateToPrint = cellsState[i][j];
			  if(stateToPrint == State.Blank)
				  spacesToAdd = " ";
			  else
				  spacesToAdd = "     ";
			  System.out.print(stateToPrint + spacesToAdd);
		  }
	  }
  System.out.println("");
  }
}