/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

public class IllegalMoveMessage {
	
	public void rubrikIsOccupied() {
		System.out.println("Illegal move. This rubik is occupied. Try to choose another one");
	}
	
	public void moveOutOfBounds() {
		System.out.println("Illegal move. Array out of bounds. Try to choose another one");
	}

}