/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqCAaaJlpubcE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqCAaaJlpubcE= >>
// ----------- >>
public class NotYourTurnMessage {

public NotYourTurnMessage() {
	System.out.println("Another Player should move");
}
}