/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/

package boundaries;

import java.util.*;

public class PlayerCheckForm {
public int check(Scanner sc) {
	int player;
	System.out.println("\nWhich player are you? (1 or 2)");
	player = sc.nextInt();
	return player;
}
}
