/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;



public class PlayerTwoMoveMessage {

	
  public void playerTwoMoveMesage() {
	  System.out.printf("Player #2's turn");

  }
}