/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqByjnnxbrEbw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqByjnnxbrEbw= >>
// ----------- >>
public class PlayerOneMoveMessage {
  // ----------- << method.annotations@AAAAAAFqBytJhBcpzRo= >>
  // ----------- >>
  public void playerOneMoveMessage() {
	  System.out.printf("Player #1 should perform move");

  }
// ----------- << class.extras@AAAAAAFqByjnnxbrEbw= >>
// ----------- >>
}