/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFp/VFnHES6Lt0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/VFnHES6Lt0= >>
// ----------- >>
public class RestartGameForm {

public int restartcheck() {
	int restartGame;
	Scanner sc = new Scanner(System.in);
	System.out.println("Do you want to restart the game (0 = no, 1 = yes)?");
	restartGame = sc.nextInt();
	sc.close();
	return restartGame;
}
}