/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

import java.util.Scanner;

import application.Constants;

public class RestartGameForm {

public int restartCheck(Scanner sc) {
	int restartGame;
	System.out.printf("Do you want to restart the game (%d = no, %d = yes)?",
			Constants.DONT_RESTART_CODE, Constants.AGREE_TO_RESTART_GAME);
	restartGame = sc.nextInt();
	return restartGame;
}
}