/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

public class ResultsMessage {

	public ResultsMessage(int winner) {
		if(winner == 0)
			System.out.println("You have a draw. Good luck next time");
		else
			System.out.printf("Player #%d wins. Congrats!", winner);
	}
}