/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package boundaries;

import application.Constants;

public class StartGameMessage {
	public StartGameMessage() {
		System.out.printf("Player #%d please start the game", Constants.PLAYER_TO_START);
	}
}