/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 * 
 * For more details, please visit www.archetypesoftware.com.
 *
 * Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
 */
package rebel;

import rebel.Constants.*;



// ----------- << imports@AAAAAAFp/VC+okS16eU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/VC+okS16eU= >>
// ----------- >>

public class BoardData {

//	public enum State{Blank, X, O};
	private int n = 3;
	private State[][] cellsState;
	private int moveCount = 0;
	private int currentPlayer = Constants.SECOND_PLAYER;

	public int getN() {
		return n;
	}


	public int getCurrentPlayer() {
		return currentPlayer;
	}

	public void setCurrentPlayer(int currentPlayer) {
		this.currentPlayer = currentPlayer;
	}

	// ----------- << attribute.annotations@AAAAAAFqB6bHtEni1gI= >>
	// ----------- >>
	private int playerTurn;

	// ----------- << attribute.annotations@AAAAAAFqEWBgTiHmyJM= >>
	// ----------- >>
	public BoardData() {
		this.cellsState = new State[n][n];
		this.cleanBoard();
	}

	// ----------- << attribute.annotations@AAAAAAFqEWBgTiHlAa4= >>
	// ----------- >>

	public State[][] getCellsState() {
		return cellsState;
	}

	public int getPlayerTurn() {
		return playerTurn;
	}

	//  public Board get() {
	//    return ;
	//  }


	public void setCellsState(State[][] cellsState) {
		this.cellsState = cellsState;
	}

	public void setPlayerTurn(int playerTurn) {
		this.playerTurn = playerTurn;
	}

//	  public void set(Board ) {
//	    this. = ;
//	  }
//	
//	  public void link(Board _) {
//	    if (_ != null) {
//	      _.unlink();
//	      _.set(this);
//	    }
//	
//	    unlink();
//	    set(_);
//	  }
//	
//	
//	
//	  public void unlink() {
//	    if (get() != null) {
//	      get().set(null);
//	      set(null);
//	    }
//	  }

	// ----------- << method.annotations@AAAAAAFqByNRLhVau8Q= >>
	// ----------- >>
	public boolean isRubricAvailable(int x, int y) {
		if(cellsState[x][y]==State.Blank)
			return true;
		else
			return false;
	}
	// ----------- << method.annotations@AAAAAAFqByPyCBWKRRg= >>
	// ----------- >>
	public boolean checkDraw() {
        if(moveCount == (Math.pow(n, 2) - 1))
            return true;
        else
        	return false;
        
		
	}
	
	public boolean checkWin(int x, int y) {
		State cellToCheck = cellsState[x][y];
        for(int i = 0; i < n; i++){
            if(cellsState[x][i] != cellToCheck)
                break;
            if(i == n-1){
                //report win
            	return true;
            }
        }

        //check row
        for(int i = 0; i < n; i++){
            if(cellsState[i][y] != cellToCheck)
                break;
            if(i == n-1){
                //report win
            	return true;
            }
        }

        //check diag
        if(x == y){
            //we're on a diagonal
            for(int i = 0; i < n; i++){
                if(cellsState[i][i] != cellToCheck)
                    break;
                if(i == n-1){
                    //report win
                	return true;
                }
            }
        }
        
      //check anti diag
        if(x + y == n - 1){
            for(int i = 0; i < n; i++){
                if(cellsState[i][(n-1)-i] != cellToCheck)
                    break;
                if(i == n-1){
                    //report win
                	return true;
                }
            }
        }
        return false;
	}
	// ----------- << method.annotations@AAAAAAFqBu0O2RT7kLA= >>
	// ----------- >>
	public void registerMove(int x, int y, State state) {
		if(isRubricAvailable(x, y) == true) {
			cellsState[x][y] = state;
			moveCount++;
		}
		else
			//TODO
			System.out.println("Rubrik already occupied please change your move");
	}

	public void cleanBoard() {
		for(int i = 0; i < n;i++) {
			for(int j = 0; j < n;j++) {
				cellsState[i][j] = State.Blank;
			}
		}
	}
	// ----------- << class.extras@AAAAAAFp/VC+okS16eU= >>
	// ----------- >>

	public void switchPlayer() {
		if(currentPlayer == Constants.FIRST_PLAYER)
			currentPlayer = Constants.SECOND_PLAYER;
		else if(currentPlayer == Constants.SECOND_PLAYER)
			currentPlayer = Constants.FIRST_PLAYER; 
		
	}
}