/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package rebel;

import java.util.*;
import java.time.*;
import rebel.BoardData.State;



// ----------- << imports@AAAAAAFp/XV7kkrpHNo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/XV7kkrpHNo= >>
// ----------- >>
public class GameBoardDisplay {
  // ----------- << method.annotations@AAAAAAFqBrtQsRKf/Ic= >>
  // ----------- >>
  public void presentBoard(BoardData board, int n) {
	  String spacesToAdd;
	  State cellsState[][] = board.getCellsState();
	  State stateToPrint;
	  System.out.println("Tic Tac Toe Board");
	  	  for(int i = 0; i < n;i++) {
		  System.out.println();
		  for(int j=0;j < n;j++) {
			  stateToPrint = cellsState[i][j];
			  if(stateToPrint == State.Blank)
				  spacesToAdd = " ";
			  else
				  spacesToAdd = "     ";
			  System.out.print(stateToPrint + spacesToAdd);
		  }
	  }
  System.out.println("");
  }
  // ----------- << method.annotations@AAAAAAFqBtEJWBQISfs= >>
  // ----------- >>
  public void showMoveOnBoard() {
  // ----------- << method.body@AAAAAAFqBtEJWBQISfs= >>
  // ----------- >>
  }
  // ----------- << method.annotations@AAAAAAFqBuXO1hRj0gs= >>
  // ----------- >>
  public void move() {
  // ----------- << method.body@AAAAAAFqBuXO1hRj0gs= >>
  // ----------- >>
  }
// ----------- << class.extras@AAAAAAFp/XV7kkrpHNo= >>
// ----------- >>
}