/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package rebel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFqByuIZRcryk8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFqByuIZRcryk8= >>
// ----------- >>
public class PlayerTwoMoveMessage {
  // ----------- << method.annotations@AAAAAAFqBy1c+xe+MQM= >>
  // ----------- >>
  public void playerTwoMoveMesage() {
	  System.out.printf("Player #2 should perform move");

  }
// ----------- << class.extras@AAAAAAFqByuIZRcryk8= >>
// ----------- >>
}