/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 * 
 * For more details, please visit www.archetypesoftware.com.
 *
 * Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
 */
package rebel;

import java.util.*;

import boundaries.ChooseYourXPositionMessage;
import boundaries.ChooseYourYPositionMessage;
import boundaries.GameBoardDisplay;
import boundaries.IllegalMoveMessage;
import boundaries.NotYourTurnMessage;
import boundaries.PlayerCheckForm;
import boundaries.PlayerOneMoveMessage;
import boundaries.PlayerTwoMoveMessage;
import boundaries.RestartGameForm;
import boundaries.ResultsMessage;

import rebel.BoardData.State;
import rebel.Constants;


public class PlayGameController {
	private int currentPlayer = 2;
	private BoardData boardData = new BoardData();

	public PlayGameController() {
		playGame();
	}

	public void playGame() {
		int x, y, currentPlayerAccordingToBoard, playerTryingToMove;
		int restartGame;
		boolean notYourTurn;
		boolean legalMove;
		PlayerCheckForm playerCheckForm = new PlayerCheckForm();
		RestartGameForm restartForm= new RestartGameForm();
		ChooseYourXPositionMessage chooseX = new ChooseYourXPositionMessage();
		ChooseYourYPositionMessage chooseY = new ChooseYourYPositionMessage();
		GameBoardDisplay boardDisplay = new GameBoardDisplay();
		PlayerTwoMoveMessage msg2Move = new PlayerTwoMoveMessage();
		PlayerOneMoveMessage msg1Move = new PlayerOneMoveMessage();

		do {
			boardData.switchPlayer();
			currentPlayerAccordingToBoard = boardData.getCurrentPlayer();

			if(currentPlayerAccordingToBoard == Constants.FIRST_PLAYER)
				msg1Move.playerOneMoveMessage();
			else if(currentPlayerAccordingToBoard == Constants.SECOND_PLAYER)
				msg2Move.playerTwoMoveMesage();

			do {
				playerTryingToMove = playerCheckForm.check();

				if(playerTryingToMove != currentPlayerAccordingToBoard) {
					new NotYourTurnMessage();
					notYourTurn = true;
				}
				else
					notYourTurn = false;
			}while (notYourTurn == true);

			do{
				x = chooseX.choose(currentPlayerAccordingToBoard);
				y = chooseY.choose(currentPlayerAccordingToBoard);


				if(boardData.isRubricAvailable(x, y)) {
					move(x,y);
					legalMove = true;
				}
				else {
					new IllegalMoveMessage();
					legalMove = false;
				}
			}while(legalMove == false);
			boardDisplay.presentBoard(boardData, boardData.getN());


			restartGame = restartForm.restartcheck();
			if(restartGame == 1)
				restartGame();
		}
		while (!boardData.checkDraw() && !boardData.checkWin(x,y));
		results();
	}
	// ----------- << method.annotations@AAAAAAFqBulsxhSBMcE= >>
	// ----------- >>
	public void move(int x, int y) {
		boardData.registerMove(x, y, State.values()[boardData.getCurrentPlayer()]);
	}
	// ----------- << method.annotations@AAAAAAFqB7omw0pLs34= >>
	// ----------- >>
	public void results() {
		ResultsMessage resMes;
		if(boardData.checkDraw()) {
			resMes = new ResultsMessage(0);
		}
		else {
			int winner = boardData.getCurrentPlayer();
			resMes = new ResultsMessage(winner);
		}
	}

	public void switchPlayer() {
		if(currentPlayer == Constants.FIRST_PLAYER)
			currentPlayer = Constants.SECOND_PLAYER;
		else if (currentPlayer == Constants.SECOND_PLAYER)
			currentPlayer = Constants.FIRST_PLAYER;
	}
	public void restartGame() {
		boardData.cleanBoard();
	}
	// ----------- << class.extras@AAAAAAFp/VrNYETRfeE= >>
	// ----------- >>
}