/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package rebel;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFp/VFnHES6Lt0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFp/VFnHES6Lt0= >>
// ----------- >>
public class RestartGameMessage {
// ----------- << class.extras@AAAAAAFp/VFnHES6Lt0= >>
// ----------- >>
}